# Generated by Django 3.0.7 on 2020-06-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product',
        ),
    ]
